// JavaScript source code
//This source code has been taken and modified from https://www.sitepoint.com/simple-javascript-quiz/
//This code is being used for testing purposes
function quizFunction() {
    const myQuestions = [
    {question: "For the following patient, please select the MOST LIKELY diagnosis.\n<br/><br/>Q.1   A 25 year old Asian man spend his days at home compulsively playing internet games, and risks losing his job.\n", answers: {a : "Asperger's Syndrome", b : "Agoraphobia", c : "Depression", d : "Generalised Anxiety Disorder", e : "Internet Gaming Disorder", f : "Paranoid Schizophrenia", g : "Panic Disorder", h : "Schizoid Personality Disorder", i : "Social Anxiety", j : "Specific Anxiety"}, correctAnswer: "e"},
{question: "For the following question, please select the MOST ACCURATE answer. \n<br/><br/>Q.2   The brain region or system where Cannabinoid CB2 receptors are principally found.\n", answers: {a : "Basal ganglia", b : "Cerebellum", c : "Dorsolateral-prefrontal cortex", d : "Gut mucosa", e : "Hippocampus", f : "Immune system", g : "Reticular activating system"}, correctAnswer: "f"},
{question: "For the following historical figure, please select the MOST ACCURATE answer. \n<br/><br/>Q.3   The concept or treatment with which Philippe Pinel is most closely associated.\n", answers: {a : "Description of catatonia", b : "Description of folie a deux", c : "Description of shell shock", d : "Electroconvulsive therapy", e : "Hypnosis", f : "Importance of heredity in mental illness", g : "Insulin coma therapy", h : "Treating patients without restraint", i : "Unconscious communication"}, correctAnswer: "h"},
{question: "For the following question, please select the MOST ACCURATE answer. \n<br/><br/>Q.4   A legal term meaning 'intent to do harm'. \n", answers: {a : "Actus reus", b : "Compos mentis", c : "Durham rule", d : "Habeas corpus", e : "M'Naghten rule", f : "Mens rea", g : "Res judicita", h : "Volenti non fit injuria"}, correctAnswer: "f"},
{question: "For the following question, please select the MOST ACCURATE answer. \n<br/><br/>Q.5   A psychotropic agent commonly causing weight loss.\n", answers: {a : "Aripiprazole", b : "Buspirone", c : "Carbamazepine", d : "Lamotrigine", e : "Lithium", f : "Moclobemide", g : "Topiramate"}, correctAnswer: "g"},
{question: "For the following question, please select the MOST ACCURATE answer. \n<br/><br/>Q.6   The fourth dimension of temperament in Robert Cloninger's model of personality, based on his Temperament and Character Inventory (the other three dimensions being: novelty seeking, harm avoidance, persistence).\n", answers: {a : "Cooperativeness", b : "Conscientiousness", c : "Introversion", d : "Neuroticism", e : "Openness to experience", f : "Reward dependence", g : "Self-directedness", h : "Self-transcendence"}, correctAnswer: "f"},
{question: "For the following example, please select the MOST ASSOCIATED concept listed below. \n<br/><br/>Q.7  Immanuel Kant developed the 'Categorical Imperative', outlining duties towards others which govern moral actions.\n", answers: {a : "Autonomy", b : "Beneficence", c : "Consequentialism", d : "Deontology", e : "Justice", f : "Non-maleficence", g : "Teleology", h : "Universalism", i : "Utilitarianism"}, correctAnswer: "d"},
{question: "For the following question, please select the MOST ACCURATE answer listed below.\n<br/><br/>Q.8   Not an aspect of behavioural epigenetics.\n", answers: {a : "A father's increasing age causing changes in sperm with increased risk of schizophrenia in his offspring", b : "Addictive substances altering gene expression and increasing tendency to addiction", c : "DNA methylation", d : "DNA sequence alteration", e : "Environmental effects", f : "Epigenome modifications by childhood trauma", g : "Histone acetylation", h : "Nurture"}, correctAnswer: "d"},
{question: "For the following example, please select the MOST ACCURATE psychological defence mechanism listed below. \n<br/><br/>Q.9   Alice is a 54 year old secretary who is unhappy with her boss and wants to leave her job, but feels guilty about this. She becomes very flattering towards her boss, praising her to other staff and giving her a gift 'in appreciation'.\n", answers: {a : "Denial", b : "Displacement", c : "Dissociation", d : "Projection", e : "Regression", f : "Repression", g : "Reaction formation", h : "Sublimation"}, correctAnswer: "g"},
{question: "For the following question, please select the MOST ACCURATE answer. \n<br/><br/>Q.10   The most common Personality Disorder in community adult populations in Western countries, based on a systematic review and meta-analysis.\n", answers: {a : "Antisocial Personality Disorder", b : "Avoidant Personality Disorder", c : "Borderline Personality Disorder", d : "Dependent Personality Disorder", e : "Histrionic Personality Disorder", f : "Narcissistic Personality Disorder", g : "Obsessive-Compulsive Personality Disorder", h : "Paranoid Personality Disorder", i : "Schizoid Personality Disorder", j : "Schizotypal Personality Disorder"}, correctAnswer: "g"},
{question: "For the following question, please select the MOST APPROPRIATE disorder from the list below. \n<br/><br/>Q.11   Has borderline hypothyroidism as a risk factor.\n", answers: {a : "Binswanger disease", b : "Frontotemporal Dementia", c : "Lewy Body Dementia", d : "Mixed Anxiety-Depressive Disorder", e : "Obsessive Compulsive Disorder", f : "Panic Disorder", g : "Rapid-Cycling Bipolar Disorder", h : "Wernicke's encephalopathy", i : "William's Syndrome"}, correctAnswer: "g"},
{question: "For the following patient, please choose the MOST APPROPRIATE explanation from the list below.\n<br/><br/>Q.12    Based on previous traumatic experiences, Belinda has developed a belief that it is futile to do anything to escape aversive consequences. \n", answers: {a : "Learned helplessness", b : "Post-Traumatic Stress Disorder", c : "Borderline Personality Disorder", d : "Aggression turned inward", e : "Operant conditioning", f : "Classical conditioning", g : "Object loss", h : "Negative attributional style"}, correctAnswer: "a"},
{question: "For the following question, please select the MOST ACCURATE answer listed below.\n<br/><br/>Q.13     Not an example of Autism Spectrum Disorder.\n", answers: {a : "Angelo is very attached to his favourite childhood toy, a spaceman action figure, and dislikes change", b : "Asperger's Disorder", c : "Autistic disorder", d : "Billy, a 5 year old boy, repetitively stacks cans on top of one another and avoids eye contact", e : "Li has difficulty interpreting social cues and body language", f : "Mara, a software coder, eats lunch alone at her desk and likes to watch a spinning top", g : "Pervasive developmental disorder not otherwise specified", h : "Ravi is aged 3 but has still not spoken. He often sits and rocks", i : "Rett's disorder"}, correctAnswer: "i"},
{question: "For the following patient, please select the MOST LIKELY syndrome listed below. \n<br/><br/>Q.14   A 38 year old woman frequently visits her general practitioner with multiple somatic complaints. She has done this since her twenties. \n", answers: {a : "Briquet's Syndrome", b : "Capgras Syndrome", c : "Charles Bonnet Syndrome", d : "Cotard's Syndrome", e : "De Clerambault's Syndrome", f : "Fregoli Syndrome", g : "Ganser Syndrome", h : "Korsakoff syndrome", i : "Munchhausen Syndrome"}, correctAnswer: "a"},
{question: "For the following patient, please select the MOST APPROPRIATE next investigation to order. \n<br/><br/>Q.15    A 21 year old woman with no history of mental illness presents with disorganised behaviour, delusions and a seizure after a week of a viral illness. CT head scan is normal.\n", answers: {a : "Copper levels", b : "Full blood count", c : "HIV serology", d : "Lumbar Puncture", e : "nMDA-r antibodies and ANA", f : "Renal Function tests", g : "Syphilis serology", h : "Thyroid function tests", i : "Urinary drug screen", j : "Vitamin studies"}, correctAnswer: "d"},
{question: "From the following list, please select the MOST APPROPRIATE assessment instrument for the patient described. \n<br/><br/>Q.16    A 60 year old man with a diagnosis of Schizophrenia presents with poor self care, lip smacking and tongue protrusion.\n", answers: {a : "Abnormal Involuntary Movement Scale", b : "Beck Depression Inventory", c : "Brief Psychiatric Rating Scale", d : "Global Assessment of Function Scale", e : "Hamilton Scale for Depression", f : "Positive and Negative Syndrome Scale", g : "Quality of Life Scale", h : "Simpson-Agnus Scale", i : "Social and Occupation Functional Assessment"}, correctAnswer: "a"},
{question: "For the following patient, please select the MOST LIKELY risk factor for her condition from the list below.\n<br/><br/>Q.17    A 69 year old woman taking risperidone is admitted acutely with rigidity, temperature of 38 degrees and confusion. On investigation she has an elevated creatinine kinase, leucocytosis and mildly elevated liver enzymes.\n", answers: {a : "Benzodiazepine dependency", b : "Cigarette smoking", c : "Dehydration", d : "Family history of anxiety disorder", e : "Family history of depression", f : "Female sex", g : "Hyperthyroidism", h : "Hypothyroidism"}, correctAnswer: "c"},
{question: "For the following question, please choose the MOST ACCURATE answer.\n<br/><br/>Q.18    Zuclopenthixol acetate should not be used in combination with which of the following antidepressants because of the potential for an interaction through shared hepatic metabolism.\n", answers: {a : "Citalopram", b : "Imipramine", c : "Mirtazapine", d : "Paroxetine", e : "Sertraline", f : "Tranylcypromine", g : "Venlafaxine"}, correctAnswer: "d"},
{question: "For the following question, please select the MOST ACCURATE answer listed below.\n<br/><br/>Q.19    Not an appropriate action in the pre-psychotic phase for a patient presenting for the first time.\n", answers: {a : "Consideration of a psychotic disorder", b : "Employment Support", c : "Family Education", d : "Interpersonal management", e : "Management of co-morbid depression", f : "Management of problematic substance use", g : "Prescription of antipsychotic medication", h : "Psychoeducation", i : "Regular family contact", j : "Regular monitoring of mental state"}, correctAnswer: "g"},
{question: "For the following patient, please select the MOST APPROPRIATE diagnosis.\n<br/><br/>Q.20    A 79 year old woman living on a farm is brought in by her daughter with a history of confused episodes. She has tremor and festination, and is annoyed by 'tiny nuns who she says sit in the pine trees outside her window.\n", answers: {a : "Alzheimer's disease", b : "Chronic subdural haematoma", c : "Left frontal meningioma", d : "Lewy-body dementia", e : "Multi-infarct dementia", f : "Multiple sclerosis", g : "Normal pressure hydrocephalus", h : "Pick's disease", i : "Right middle cerebral infarct", j : "Subarachnoid haemorrhage"}, correctAnswer: "d"},
{question: "For the following patient, please select the MOST LIKELY country of origin.\n<br/><br/>Q.21    A 43 year old male immigrant's family tell his doctor that he is suffering from Khyal Cap (wind attacks).\n", answers: {a : "Botswana", b : "Cambodia", c : "Cuba", d : "Indonesia", e : "Nigeria", f : "Papua New Guinea", g : "Sudan", h : "Taiwan", i : "Yemen", j : "Zimbabwe"}, correctAnswer: "b"},
{question: "For the following aspect of phenomenology, please select the MOST ACCURATE answer.\n<br/><br/>Q.22   An example of a Schneiderian first rank symptom.\n", answers: {a : "Abulia", b : "Affective flattening", c : "Auditory Hallucinations experienced as a running commentary", d : "Auditory hallucinations experienced as two or more voices talking amongst themselves", e : "Delusions of misidentification", f : "Delusions of reference", g : "Ego boundary blurring", h : "Persecutory delusions", i : "Secondary delusions", j : "Thought diffusion"}, correctAnswer: "c"},
{question: "For the following question, please select the MOST ACCURATE answer.\n<br/><br/>Q.23    The percentage of the population who will meet the diagnostic criteria for schizophrenia over their lifetime.\n", answers: {a : "0.01", b : "0.1", c : "0.2", d : "0.5", e : "1.0", f : "2.5", g : "10"}, correctAnswer: "e"},
{question: "For the following receptor group, please choose the MOST ACCURATE answer.\n<br/><br/>Q.24    A function regulated by 5HT3 receptors.\n", answers: {a : "Anxiety", b : "Circadian rhythms", c : "Cognition", d : "Mood", e : "Nausea", f : "Stress response", g : "Thermoregulation"}, correctAnswer: "e"},
{question: "For the following clinical situation, please choose the MOST APPROPRIATE intervention from the list below.\n<br/><br/>Q.25    Medication to co-administer when starting someone on clozapine.\n", answers: {a : "Docusate Sodium", b : "Docusate sodium and Sennoside B", c : "Fleet Enema", d : "Lactulose", e : "Lax-sachets", f : "Magnesium hydroxide", g : "Microlax enema", h : "Movicol", i : "Psyllium husk powder"}, correctAnswer: "b"},
{question: "For the following vignette, please select the MOST ACCURATE phenomenoloy demonstrated, from the list below.\n<br/><br/>Q.26    Aroha, a 27 year old woman with a history of schizophrenia, says that the pins and needles she experiences are due to 'space rays' being fired at her.\n", answers: {a : "Bizarre Delusion", b : "Delusion of Control", c : "Delusion of Reference", d : "Mood-congruent Delusion", e : "Nihilistic Delusion", f : "Paranoid Delusion", g : "Passivity Delusion", h : "Somatic Delusion"}, correctAnswer: "h"},
{question: "For the following fictional clinical scenario, please select the MOST APPROPRIATE description listed below.\n<br/><br/>Q.27    A psychiatrist in a movie has a sexual encounter with the brother of the patient she is treating with psychodynamic psychotherapy, while meeting with him to obtain collateral information.  \n", answers: {a : "Boundary violation", b : "Displacement", c : "Empathic failure", d : "Mirroring", e : "Objectification", f : "Parallel process", g : "Positive transference", h : "Projective identification"}, correctAnswer: "a"},
{question: "For the following patient, please select the MOST APPROPRIATE next management step from the list below.\n<br/><br/>Q.28    Vicky, a 20 year old woman, has been in the acute inpatient ward for 3 weeks with first episode psychosis.  She is being treated with Risperidone ' 1 mg initially, then 2mg for the past 17 days. She remains psychotic.\n", answers: {a : "Add Lithium", b : "Add regular benzodiazepine", c : "Add a selective serotonin reuptake inhibitor", d : "Augment with Aripiprazole", e : "Change to Olanzapine", f : "Increase dose of Risperidone to 4 mg", g : "Increase dose of Risperidone to 6mg"}, correctAnswer: "f"},
{question: "Please select the MOST APPROPRIATE answer demonstrated by the following scenario.\n<br/><br/>Q.29   Sarah, aged 7, presents with her foster parents of three years.  They say their key difficulty with Sarah is demanding behaviour in the supermarket and similar settings. They report that they ignore her pleas for sweets for up to 15 minutes, but eventually they have to give her a chocolate bar to avoid a half hour tantrum at the supermarket checkout.\n", answers: {a : "Behavioural Contingencies", b : "Eriksonian Stage ' Autonomy vs Shame/Doubt", c : "Eriksonian Stage ' Identity vs Role Confusion", d : "Insecure attachment ' avoidant type", e : "Insecure attachment ' disorganised insecure type", f : "Learned helplessness", g : "Patterson's cycle of coercion"}, correctAnswer: "g"},
{question: "For the following clinical example, please select the MOST APPROPRIATE investigation.\n<br/><br/>Q.30    A 63 year old woman has suspected neurotoxicity from lithium treatment, despite her serum lithium levels being in the quoted normal range. \n", answers: {a : "ECG", b : "EEG", c : "MoCA", d : "MRI scan", e : "PET scan", f : "SPECT scan", g : "Serum potassium", h : "Serum TSH"}, correctAnswer: "b"},
{question: "For the following clinical example, please select the MOST APPROPRIATE  diagnosis.\n<br/><br/>Q.31    A 50 year old man presents with concerns that his wife has been unfaithful. He has a two year history of these beliefs but is otherwise functioning well. No collateral evidence supports his concerns. \n", answers: {a : "Brief Psychotic Disorder", b : "Delusional Disorder", c : "Jealousy", d : "Major Depressive Disorder", e : "Obsessive Compulsive Disorder", f : "Paranoid Personality disorder", g : "Relationship Difficulties", h : "Schizoaffective Disorder", i : "Schizophrenia", j : "Schizophreniform Disorder", k : "Schizotypal Personality Disorder"}, correctAnswer: "b"},
{question: "For the following clinical situation, please select the MOST ACCURATE outcome listed below.\n<br/><br/>Q.32    Very preterm birth (less than 32 weeks gestation).\n", answers: {a : "Cerebral palsy in more than 30% of survivors", b : "Higher incidence of reactive attachment disorder", c : "Inattention, anxiety, and socio-emotional difficulties in childhood", d : "Lower rates of eating disorders in adulthood", e : "Minimal effect upon thalamocortical and corticostriatial connectivity", f : "Significantly increased rates of conduct disorder in late adolescence", g : "Similar rates in adulthood of bipolar affective disorder to term controls"}, correctAnswer: "c"},
{question: "For the following scenario, please select the MOST LIKELY  cause listed below.\n<br/><br/>Q.33    A 35 year old office worker goes tramping and on the second day, suffers from moderate headaches and sleepiness.\n", answers: {a : "Alcohol Withdrawal", b : "Caffeine Withdrawal", c : "Cluster Headache", d : "Depression", e : "Meningitis", f : "Migraine", g : "Sensory Overload", h : "Chronic Fatigue", i : "Tension Headache"}, correctAnswer: "b"},
{question: "For the following example, please select the MOST ACCURATE answer listed below. \n<br/><br/>Q.34   A substrate metabolized by MAO-B but not MAO-A.\n", answers: {a : "Acetylcholine", b : "Dopamine", c : "Histamine", d : "Noradrenaline", e : "Phenylethylamine", f : "Serotonin", g : "Tyramine"}, correctAnswer: "e"},
{question: "For the following question, please select the MOST ACCURATE answer listed below.\n<br/><br/>Q.35    Not associated with Ganser syndrome.\n", answers: {a : "Balderdash syndrome", b : "Conversion disorder", c : "Decreased state of consciousness", d : "Dissociative amnesia", e : "Dissociative disorder", f : "Fugue state", g : "Gedankenlautverden", h : "Hysterical pseudodementia", i : "Prison psychosis", j : "Syndrome of approximate answers", k : "Visual pseudohallucinations", l : "Vorbeireden"}, correctAnswer: "g"},
{question: "For the following patient, please select the MOST APPROPRIATE next psychometric test.\n<br/><br/>Q.36    David is a 12 year old boy, referred due to behavioural problems and poor learning in the classroom. The team psychologist has completed a WISC which shows a Full Scale IQ of 68.\n", answers: {a : "Adaptive Behaviour Assessment Scale (ABAS)", b : "Autism Diagnostic Observation Scale (ADOS)", c : "Child Behaviour Checklist (CBCL/Rutter)", d : "Conners Comprehensive Behaviour Rating Scale", e : "(Conners CBRS)", f : "Kiddie Schedule for Affective Disorders and Schizophrenia (K-SADS)", g : "Millon Adolescent Personality Inventory (MAPI)", h : "Weschler Intelligence Scale (WAIS)"}, correctAnswer: "a"},
{question: "For the following symptom, please select the MOST ACCURATE description.\n<br/><br/>Q.37    A tic.\n", answers: {a : "A peculiar and characteristic individual style of movement", b : "An involuntary, sudden, rapid, recurrent, non-rhythmic motor movement or vocalisation", c : "An urge to move the legs, accompanied by unpleasant sensations, relieved by movement", d : "Disordered muscle tone", e : "Distortion of voluntary movements with involuntary muscle activity", f : "Excessive motor activity associated with a feeling of inner tension", g : "Odd and inappropriate facial expressions unrelated to the situation", h : "Persistent eating of non-nutritive non-food substances"}, correctAnswer: "b"},
{question: "For the following topic, please select the MOST ACCURATE statement from the list below.\n<br/><br/>Q.38    Diagnostic and Classificatory systems.\n", answers: {a : "Adam Guillaume and his grandson Jean Bertrand were the founders of the ICD system", b : "Current classification systems in psychiatry are aetiologically based, rather than descriptive", c : "DSM-III was published in 1985", d : "Greater focus on validity rather than reliability tends to create increasing numbers of diagnostic categories", e : "ICD-11 will be focussed on clincial utility", f : "Operational diagnostic criteria were first introduced to the DSM system with DSM-IV", g : "Research Domain Criteria (RDoC), linked to neurobiological correlates, pre-dated the DSM system", h : "The Zone of rarity' is more often present in psychiatric disorders than in the rest of medicine"}, correctAnswer: "e"},
{question: "For the following example, please select the MOST ACCURATE  statement listed below.\n<br/><br/>Q.39    The rate of misdiagnosis of conversion disorder due to missing an occult, causative pathology.\n", answers: {a : "Decreased in more recent years due to the widespread availability of advanced neuroimaging such as MRI scans", b : "Has been very low (less than 5%) since the 1970s", c : "Increased in more recent years due to the diagnosis of conversion disorder being made more often in primary care settings", d : "Stayed around 60%, i.e. the diagnosis of conversion disorder is more often wrong than right", e : "Stayed the same since DSM-III in 1980 as there have been no changes in the classification of conversion disorders since then"}, correctAnswer: "b"},
{question: "For the following question, please select the MOST ACCURATE  answer.\n<br/><br/>Q.40    The third dimension according to which Emil Kraepelin classified mixed mood states ' the other two being mood and motor activity.\n", answers: {a : "Anxiety", b : "Distractibility", c : "Hazardous behaviour", d : "Irritability", e : "Libido", f : "Self esteem", g : "Sleep", h : "Speed of thought"}, correctAnswer: "h"},
{question: "For the following patient, please select the MOST APPROPRIATE clinical stage. \n<br/><br/>Q.41   Sam, a young man aged 18, first presented four months ago with paranoid delusions and auditory hallucinations. Despite trials with three antipsychotics, his auditory hallucinations remain.\n", answers: {a : "Stage 0", b : "Stage 1a", c : "Stage 1b", d : "Stage 2", e : "Stage 3a", f : "Stage 3b", g : "Stage 3c", h : "Stage 4"}, correctAnswer: "e"},
{question: "For the following patient, please select the MOST APPROPRIATE treatment option.\n<br/><br/>Q.42    Henry, aged 79, develops muscle twitching while still unconscious after his ECT treatment ' reapplication of the EEG shows this to be a tardive seizure.\n", answers: {a : "Carbamazepine orally", b : "Diazepam intramuscularly", c : "Diazepam intravenously", d : "Midazolam intravenously", e : "Mirtazapine orally", f : "Olanzapine oral wafer", g : "Olanzapine short-acting injection", h : "Re-treat with ECT immediately", i : "Sodium valproate orally", j : "Terminate ECT course"}, correctAnswer: "d"},
{question: "For the following historical development, please select the MOST ACCURATE answer.\n<br/><br/>Q.43    Developed Interpersonal and Social Rhythm Therapy.\n", answers: {a : "Adrian Wells", b : "Anthony Bateman", c : "Ellen Frank", d : "Gerald Klerman", e : "John Teasdale", f : "Marsha Linehan", g : "Myrna Weissman", h : "Steven Hayes"}, correctAnswer: "c"},
{question: "For the following example, please select the MOST ACCURATE description listed below.\n<br/><br/>Q.44    The smell of fresh muffins in a bakery makes a man's mouth water as he waits to be served.\n", answers: {a : "Classical conditioning", b : "Counter-conditioning", c : "Episodic memory", d : "Operant conditioning", e : "Semantic memory", f : "Sensory memory", g : "Shaping", h : "Short-term memory"}, correctAnswer: "a"},
{question: "For the following patient, please select the MOST APPROPRIATE description of her clinical situation.\n<br/><br/>Q.45    Emily is 17 and has been wheelchair-bound and off school since breaking her ankle in a netball game 13 months ago.  Her surgeon has said that the bones have healed normally, however she has been experiencing increasingly severe pain in her ankle, and is unable to weight-bear.  Her ankle is cooler than the other side, and the skin looks blotchy.  She insists she is not depressed.\n", answers: {a : "She has chronic regional pain syndrome, which has developed due to underlying unrecognised depression and alexithymia", b : "She has a factitious disorder, as the fracture has fully healed", c : "Her pain is probably due to ongoing primary nociceptive input, despite the normal scans, and her ankle should be immobilised in a splint", d : "She has chronic regional pain syndrome, which is untreatable and she should complete her education by correspondence", e : "She has chronic regional pain syndrome, and part of her treatment plan should include exploring reasons for why she has been unable to transition back to school", f : "The skin appearance changes indicate that there are nutritional deficits that should be corrected", g : "She should be started on Venlafaxine as this has evidence for efficacy in chronic pain in adolescents"}, correctAnswer: "e"},
{question: "For the following statement, please select the MOST ACCURATE answer.\n<br/><br/>Q.46    The majority of noradrenergic neurons in the brain arise from this anatomic structure.\n", answers: {a : "Dorsal raphe nucleus", b : "Dorsal stratum", c : "Hippocampus", d : "Locus coeruleus", e : "Median raphe nucleus", f : "Nucleus basalis of Meynert", g : "Ventral tegmental area"}, correctAnswer: "d"},
{question: "For the following question, please select the MOST ACCURATE answer.\n<br/><br/>Q.47    A feature that does not support the specifier 'with good prognostic features in a patient with Schizophreniform Disorder.\n", answers: {a : "Blunted affect", b : "Good premorbid occupational functioning", c : "Good premorbid social functioning", d : "Normal cognitive functioning", e : "Onset of symptoms within four weeks of first change in functioning or behavior", f : "Symptoms are accompanied by confusion", g : "Symptoms are accompanied by perplexity"}, correctAnswer: "a"},
{question: "For the following example, please select the LEAST ACCURATE statement listed below.\n<br/><br/>Q.48    Collectivist cultures.\n", answers: {a : "Are known for interconnectedness with others playing a central role in each person's identity", b : "Are more complex to consider using Beauchamp and Childress's principles", c : "Are more likely to explain something via external causality than self-direction", d : "Are less context dependent in their perceptions", e : "Emphasize the family above individual needs or desires", f : "Tend to accept that different groups have different values", g : "Value decisions made by the family or family elders over individual autonomy", h : "Value work group or family goals above individual achievements"}, correctAnswer: "d"},
{question: "Please select the MOST APPROPRIATE answer illustrated by the scenario.\n<br/><br/>Q.49    Ralph is a 15 year old boy who has recently told his parents that he's bisexual. His family have told him he's confused due to his mother being overwhelmed in his early life by the arrival of a baby sister when he was only 11 months old. \n", answers: {a : "Eriksonian Stage ' Autonomy vs Shame/Doubt", b : "Eriksonian Stage ' Ego Integrity vs. Despair", c : "Eriksonian Stage ' Generativity vs. Stagnation", d : "Eriksonian Stage ' Identity vs Role Confusion", e : "Eriksonian Stage ' Industry vs Inferiority", f : "Eriksonian Stage ' Initiative vs Guilt", g : "Eriksonian Stage ' Intimacy vs Isolation", h : "Eriksonian Stage ' Trust vs Mistrust"}, correctAnswer: "d"},
{question: "For the following clinical situation, please select the MOST APPROPRIATE rating scale.\n<br/><br/>Q.50    Monitoring symptoms in a patient with schizophrenia.\n", answers: {a : "AIMS", b : "BPRS", c : "GAF", d : "HAMD", e : "MADRS", f : "PANSS", g : "SANS", h : "SAPS", i : "SCID"}, correctAnswer: "b"},
{question: "For the following clinical example please select the MOST APPROPRIATE phenomenology from the list below.\n<br/><br/>Q.51    Lack of insight in severe, chronic schizophrenia.\n", answers: {a : "Anosognosia", b : "Astereognosis", c : "Autotopagnosia", d : "Cerebral achromatopsia", e : "Environmental agnosia", f : "Phonagnosia", g : "Prosopagnosia", h : "Simultagnosia"}, correctAnswer: "a"},
{question: "For the following example, please select the MOST APPROPRIATE ethical concept from the list below.\n<br/><br/>Q.52   Psychoeducation of patients.\n", answers: {a : "A Kantian categorical imperative", b : "Autonomy", c : "Beneficence", d : "Ethical relativism", e : "Justice", f : "Non-maleficence", g : "Practical wisdom", h : "Utilitarianism"}, correctAnswer: "b"},
{question: "For the following example of speech please select the MOST APPROPRIATE phenomenology from the list below.\n<br/><br/>Q.53    'Then I left Timaru and moved to... where did you get that tie?'\n", answers: {a : "Clanging", b : "Command hallucinations", c : "Delusions of control", d : "Distractibility", e : "Echolalia", f : "Knight's move thinking", g : "Perseveration", h : "Tangentiality", i : "Thought Blocking"}, correctAnswer: "d"},
{question: "For the following question, please select the MOST ACCURATE answer listed below.\n<br/><br/>Q.54    Not part of a routine physical assessment in a patient presenting with first episode psychosis.\n", answers: {a : "Anti-NMDAR antibodies", b : "Electrocardiogram", c : "Electroencephalography", d : "Electrolytes", e : "Fasting Glucose", f : "Full blood count", g : "Hepatitis Screen", h : "Lipids", i : "Neurological Examination", j : "Thyroid Function Tests", k : "Urinary Drug Screen"}, correctAnswer: "c"},
{question: "For the following question, please select the MOST APPROPRIATE answer. \n<br/><br/>Q.55    Used to treat obsessive-compulsive disorder.\n", answers: {a : "Brief psychodynamic therapy", b : "CBT-oriented group therapy", c : "Exposure and response prevention", d : "Expressive therapy", e : "Family therapy", f : "Interpersonal therapy", g : "Marital therapy", h : "Mindfulness training", i : "Motivational interviewing", j : "Systematic desensitisation"}, correctAnswer: "c"},
{question: "For the following patient please select the MOST APPROPRIATE  diagnosis from the list below.\n<br/><br/>Q.56    Bianca is a 6 year old girl who often has temper tantrums. She once set her doll's house on fire while playing and when taken to task afterwards, blamed her brother for it. She is liked by her peers, but known as a 'troublemaker' by her teachers and argues a lot with her parents. She loves her cat and looks after him well. \n", answers: {a : "Adjustment disorder with mixed disturbance of emotions and conduct", b : "Autistic spectrum disorder", c : "Conduct disorder", d : "Disruptive mood dysregulation disorder", e : "Intermittent explosive disorder", f : "Oppositional defiant disorder", g : "Psychopathy", h : "Social anxiety disorder"}, correctAnswer: "f"},
{question: "For the following patient, please select the MOST APPROPRIATE  diagnosis.\n<br/><br/>Q.57    A 52 year old man presents with a longstanding court battle against a former employee which he says is an 'attack on my character'. He says the court battle has lost him friends as they didn't side with him and betrayed him. He says this only goes to show that he's always been right to mistrust others.\n", answers: {a : "Brief Psychotic Disorder", b : "Delusional Disorder", c : "Major Depressive Disorder", d : "Narcissistic Personality disorder", e : "Obsessive Compulsive Disorder", f : "Paranoid Personality disorder", g : "Schizoaffective Disorder", h : "Schizoid Personality Disorder", i : "Paranoid schizophrenia", j : "Schizotypal Personality Disorder"}, correctAnswer: "f"},
{question: "For the following conversation please select the MOST APPROPRIATE phenomenology from the list below.\n<br/><br/>Q.58    'Is your name Margery?'<br/>'Yes.'<br/>'Are you in hospital?'<br/>'Yes.'<br/>'Are you a table?'<br/>'Yes.'\n", answers: {a : "Clanging", b : "Distractability", c : "Echolalia", d : "Incoherence", e : "Knight's move thinking", f : "Loss of goal", g : "Perseveration", h : "Tangentiality"}, correctAnswer: "g"},
{question: "For the following description, please select the MOST APPROPRIATE neurotransmitter listed below.\n<br/><br/>Q.59     Synthesized from the amino acid tyrosine.\n", answers: {a : "Acetylcholine", b : "Dopamine", c : "Gamma-aminobutyric acid", d : "Glutamate", e : "Glycine", f : "Noradrenaline", g : "Serotonin"}, correctAnswer: "b"},
{question: "For the following rating scale, please select the MOST APPROPRIATE answer listed below.\n<br/><br/>Q.60    Developed an 11-item rating scale for mania.\n", answers: {a : "Barnes", b : "Beck", c : "Brown", d : "Hamilton", e : "Hare", f : "Montgomery and Asberg", g : "Young", h : "Zung"}, correctAnswer: "g"},
{question: "For the following example, please select the MOST RELEVANT  legal concept.\n<br/><br/>Q.61    A man with a long history of theft is arrested for stealing cars after police find his fingerprints on a stolen BMW.\n", answers: {a : "Actus reus", b : "Disease of the mind", c : "Fitness to plead", d : "Forseeability", e : "Irresistible impulse", f : "Mens rea", g : "Natural Justice", h : "Provocation", i : "Sane Automatism"}, correctAnswer: "a"},
{question: "For the following patient, please select the MOST ACCURATE diagnosis from the list below.\n<br/><br/>Q.62     A 25 year old man lives alone and reports being very lonely. He says he feels inadequate and needs reassurance before attempting any activity or interpersonal interaction, for fear of humiliation.\n", answers: {a : "Antisocial Personality Disorder", b : "Avoidant Personality Disorder", c : "Borderline Personality Disorder", d : "Dependent Personality Disorder", e : "Histrionic Personality Disorder", f : "Narcissistic Personality Disorder", g : "Paranoid Personality Disorder", h : "Passive-Aggressive Personality Disorder", i : "Schizoid Personality Disorder", j : "Schizotypal Personality Disorder"}, correctAnswer: "b"},
{question: "For the following brain function, please select the MOST ACCURATE answer.\n<br/><br/>Q.63    The brain region synchronizing the synthesis of melatonin to the light/dark cycle.\n", answers: {a : "Dorsomedial nucleus", b : "Medial septal nucleus", c : "Nucleus accumbens", d : "Paraventricular nucleus", e : "Posterior nucleus", f : "Red nucleus", g : "Suprachiasmatic nucleus", h : "Ventromedial nucleus"}, correctAnswer: "g"},
{question: "For the following patient, please select the MOST LIKELY  diagnosis.\n<br/><br/>Q.64     A tall young man has a rounded body-type and is teased at school for his gynaecomastia. Investigation reveals an XXY chromosomal pattern.\n", answers: {a : "Adrenogenital syndrome", b : "Gender identity disorder", c : "Klinefelter's syndrome", d : "Polycystic ovarian syndrome", e : "Pseudohermaphroditism", f : "Transvestic Fetishism", g : "Turner's syndrome", h : "Testicular feminisation syndrome"}, correctAnswer: "c"},
{question: "For the following example of speech please select the MOST APPROPRIATE phenomenology from the list below.\n<br/><br/>Q.65    'Bulldogs are from England. They have good fish and chips there. Fish breathe underwater.'\n", answers: {a : "Bizarre Delusions", b : "Circumstantiality", c : "Clanging", d : "Derailment", e : "Distractability", f : "Knight's move thinking", g : "Paraphasias", h : "Perseveration", i : "Tangential thinking", j : "Thought Insertion"}, correctAnswer: "i"},
{question: "For the following patient, please select the MOST LIKELY diagnosis.\n<br/><br/>Q.66    Gabriella, who is being treated for psychosis, develops a headache, nausea and vomiting. Her urine sodium concentration is greater than 20 mEq/L.\n", answers: {a : "Cushings disease", b : "Graves disease", c : "Phaeochromocytoma", d : "Porphyria", e : "Psychogenic polydipsia", f : "Renal failure", g : "SIADH", h : "Wilson's disease"}, correctAnswer: "g"},
{question: "For the following PATIENT, please give the MOST ACCURATE diagnosis.\n<br/><br/>Q.67    Darius, aged 22, presents with a two year history of functional decline with poor motivation.  His family say that for the last month they have had difficulty following what he's saying and that he has been concerned about aliens harming him. They report a similar episode 18 months ago which was short-lived ' they didn't take him to see his GP then as he improved. \n", answers: {a : "Schizophrenia, continuous", b : "Schizophrenia, first episode, currently in acute episode", c : "Schizophrenia, first episode, in partial remission", d : "Schizophrenia, first episode, in full remission", e : "Schizophrenia, multiple episodes, currently in acute episode", f : "Schizophrenia, multiple episodes, currently in partial remission", g : "Schizophrenia, multiple episodes, currently in full remission", h : "Schizophreniform Disorder, with good prognostic features", i : "Schizophreniform Disorder, without good prognostic features"}, correctAnswer: "b"},
{question: "For the following example, please select the MOST ACCURATE answer.\n<br/><br/>Q.68    The first comprehensive, multi-informant epidemiological study of childhood psychopathology.\n", answers: {a : "The Achenbach System of Empirically Based Assessment Study", b : "The Avon Longitudinal Study of Parents and Children", c : "The CATIE study", d : "The Christchurch Health and Development Study", e : "The Dunedin Multidisciplinary Health and Development Study", f : "The Great Smokey Mountain Study", g : "The Isle of Wight Study", h : "The Ontario Child Health Study"}, correctAnswer: "g"},
{question: "For the following example, please select the MOST ACCURATE answer from the list below. \n<br/><br/>Q.69    A client-centered, semi-directive method of engaging intrinsic motivation to change behavior by developing discrepancy and exploring and resolving ambivalence within the client.\n", answers: {a : "12-step programme", b : "Adherence therapy", c : "Cognitive behavioural therapy", d : "Harm minimisation", e : "Motivational interviewing", f : "Prochaska & DiClemente's Wheel of Change", g : "Psychoeducation", h : "Systematic desensitisation"}, correctAnswer: "e"},
{question: "For the following patient, please select the MOST APPRIORIATE  next step in his management.\n<br/><br/>Q.70    Tanvir, a 24 year old Bangladeshi man, has been in hospital for eight weeks with his second psychotic episode.  There has been minimal improvement despite treatment with Risperidone. The dose was titrated up since admission and has been 6mg for the past 4 weeks.\n", answers: {a : "Augment with Lorazepam", b : "Augment with Ziprasidone", c : "Change to Aripiprazole", d : "Change to Clozapine", e : "Change to Olanzapine", f : "Electroconvulsive therapy", g : "Increase Risperidone to 8mg", h : "Wait a further two weeks"}, correctAnswer: "c"},
{question: "For the following question, please select the MOST ACCURATE  answer. \n<br/><br/>Q.71    Atypical depression is thought to be most closely related to which disorder listed below?\n", answers: {a : "Alcoholism", b : "Bipolar disorder", c : "Borderline personality disorder", d : "Bulimia nervosa", e : "Catatonia", f : "Panic disorder", g : "Schizophrenia"}, correctAnswer: "b"},
{question: "For the following concept, please select the LEAST ACCURATE feature listed below.\n<br/><br/>Q.72    Features of holistic Mäori concepts of health (including Te Whare Tapa Wha, Te Wheke and Nga Pou Mana).\n", answers: {a : "Cultural heritage (Taonga tuku iho)", b : "Emotions (Whatumanawa)", c : "Environment (Te ao turoa)", d : "Family (Whänau)", e : "Land base (Turangawaewae)", f : "Mental health (Hinengaro)", g : "Physical health (Tinana)", h : "Self determination (Tino rangatiratanga)", i : "Spirituality (Wairua)", j : "Uniqueness (Mana ake)", k : "Vitality (Mauri)"}, correctAnswer: "h"},
{question: "For the following symptom, please select the MOST LIKELY causative movement disorder from the list below.\n<br/><br/>Q.73     The bon-bon sign.\n", answers: {a : "Acute Dystonia", b : "Akathisia", c : "Chronic Dystonia", d : "Oculogyric Crisis", e : "Medication Induced Tremor", f : "Neuroleptic Malignant Syndrome", g : "Pseudo-parkinsonism", h : "Tardive Dyskinesia"}, correctAnswer: "h"},
{question: "For the following clinical example, please select the MOST APPROPRIATE symptom listed below.\n<br/><br/>Q.74    A sales clerk loses his ability to make change and write clearly, and cannot say whether you are holding up your thumb or index finger. \n", answers: {a : "Anosognosia", b : "Autotopagnosia", c : "Dysaesthesia", d : "Dyscalculia", e : "Dysgeusia", f : "Palinopsia", g : "Pareidolia", h : "Prosopagnosia", i : "Simultanagnosia", j : "Visual agnosia"}, correctAnswer: "d"},
{question: "For the following example, please select the MOST APPROPRIATE type of psychotherapy listed below. \n<br/><br/>Q.75    Role dispute or Role transition are two of the four areas of focus.\n", answers: {a : "Brief psychodynamic therapy", b : "CBT-oriented group therapy", c : "Exposure and response prevention", d : "Expressive therapy", e : "Family therapy", f : "Interpersonal therapy", g : "Marital therapy", h : "Mindfulness training", i : "Motivational interviewing", j : "Systematic desensitisation"}, correctAnswer: "f"},
{question: "For the following patient, please select the MOST APPROPRIATE diagnosis.\n<br/><br/>Q.76    Negative cognitions about oneself, the world and the future.\n", answers: {a : "All-or-nothing thinking", b : "Automatic thoughts", c : "Catastrophising", d : "Disqualifying the positive", e : "Emotional reasoning", f : "'Fortune teller' cognitive distortions", g : "Mislabelling", h : "Overgeneralization", i : "Personalization", j : "The cognitive triad"}, correctAnswer: "j"},
{question: "For the following condition, please choose the MOST ACCURATE associated answer.\n<br/><br/>Q.77    Linked with velocardiofacial syndrome and schizophrenia.\n", answers: {a : "CAG trinucleotide repeats", b : "Chromosome 21 linkages", c : "Chromosome 22q deletions", d : "Genetic polymorphism of acetaldehyde dehydrogenase", e : "Intermediate P450 2D6 metabolizer phenotypes", f : "P450 1A2 polymorphisms", g : "P450 3A4 polymorphisms", h : "Ultra-rapid P450 2D6 metabolizer phenotypes"}, correctAnswer: "c"},
{question: "For the following example, please select the MOST APPROPRIATE  answer from the list below.\n<br/><br/>Q.78    The most appropriate antipsychotic to use in a patient with a prolonged QTc interval.\n", answers: {a : "Amisulpride", b : "Aripiprazole", c : "Chlorpromazine", d : "Clozapine", e : "Haloperidol", f : "Olanzapine", g : "Quetiapine", h : "Ziprasidone"}, correctAnswer: "f"},
{question: "For the following clinical scenario, please select the MOST APPROPRIATE treatment for the patient.\n<br/><br/>Q.79    Barbara is a 63 year old woman who presents with dysphoric mood, irritability, panic attacks, pressured speech, agitation and suicidal ideation.\n", answers: {a : "Bupropion", b : "Carbamazepine", c : "Citalopram", d : "Lithium", e : "Nortriptyline", f : "Sodium valproate", g : "Topiramate", h : "Tranylcypromine"}, correctAnswer: "f"},
{question: "For the following patient, please select the MOST APPROPRIATE treatment choice.\n<br/><br/>Q.80     Tom is a 25 year old man who was admitted with first episode psychosis. His symptoms have completely resolved on Amisulpride. Tom would like to know how long to continue taking Amisulpride.\n", answers: {a : "Five years from the resolution of his symptoms", b : "Six months from the resolution of his symptoms", c : "Three months from the resolution of his symptoms", d : "Tom should never stop the Amisulpride", e : "Tom should only stop the Amisulpride if he's experiencing side effects", f : "Twelve months from the resolution of his symptoms", g : "Two years months from the resolution of his symptoms"}, correctAnswer: "f"},
{question: "For the following patient, please select the MOST LIKELY  diagnosis.\n<br/><br/>Q.81    Brian, aged 68, develops memory deficits and is arrested after urinating in public at a local park.\n", answers: {a : "Acting out", b : "Alzheimer's dementia", c : "Delirium", d : "Exhibitionism", e : "Frontal tumour", f : "Hypomania", g : "Late onset schizophrenia", h : "Parkinson's disease"}, correctAnswer: "b"},
{question: "For the following clinical example, please select the MOST APPROPRIATE  symptom demonstrated.\n<br/><br/>Q.82    A man in a neurological ward can copy a picture of a clockface but cannot say what the picture represents.\n", answers: {a : "Astereognosis", b : "Autotopagnosia", c : "Dysgeusia", d : "Fausse reconnaissance", e : "Jamais vu", f : "Prosopagnosia", g : "Visual agnosia", h : "Visual illusion"}, correctAnswer: "g"},
{question: "For the following clinical scenario, please select the MOST LIKELY diagnosis from the list below.\n<br/><br/>Q.83   Alice, a 45 year old woman in supported accommodation who has chronic schizophrenia, is noted to be drinking water excessively. Her serum sodium concentration is low.\n", answers: {a : "Cushings disease", b : "Graves disease", c : "Hypothyroidism", d : "Liver failure", e : "Phaeochromocytoma", f : "Porphyria", g : "Psychogenic polydipsia", h : "Renal failure", i : "SIADH", j : "Wilson's disease"}, correctAnswer: "g"},
{question: "For the following patient, please select the MOST APPROPRIATE  psychometric tool to use.\n<br/><br/>Q.84    Angela is a 12 year old girl who has been referred due to her teachers' concern about her marked inattention in class ' she often gets up before completing her work to stare out the window.\n", answers: {a : "Adaptive Behaviour Assessment Scale (ABAS)", b : "Autism Diagnostic Observation Scale (ADOS)", c : "Child Behaviour Checklist (CBCL/Rutter)", d : "Conners Comprehensive Behaviour Rating Scale", e : "(Conners CBRS)", f : "Kiddie Schedule for Affective Disorders and Schizophrenia (K-SADS)", g : "Millon Adolescent Personality Inventory (MAPI)", h : "Weschler Intelligence Scale for Children (WISC)"}, correctAnswer: "d"},
{question: "For the following clinical scenario, please select the MOST APPROPRIATE intervention.\n<br/><br/>Q.85     A 19 year young old man with psychosis who was started on Risperidone two days ago presents with his eyes rolled back in his head. He is in acute distress and discomfort. \n", answers: {a : "Benztropine 2mg intramuscularly", b : "Benzotropine 2mg intravenously across several minutes.", c : "Benztropine 2mg orally", d : "Diazepam 5mg intramuscularly", e : "Lorazepam 2mg intramuscularly", f : "Lorazepam 2mg intravenously across several minutes.", g : "Lorazepam 2mg orally", h : "Propranolol 10mg orally"}, correctAnswer: "b"},
{question: "For the clinical presentation, please select the MOST APPROPRIATE initial investigation from the list below.\n<br/><br/>Q.86    Molly, aged 50, has a longstanding bipolar disorder treated with lithium carbonate. She develops difficulty swallowing.\n", answers: {a : "AIMS assessment", b : "Barium swallow", c : "Chest X-Ray", d : "CT head and neck", e : "EEG", f : "Gastroscopy", g : "Lateral neck X-Ray", h : "MRI scan", i : "Serum calcium"}, correctAnswer: "g"},
{question: "For the following example, please select the MOST ACCURATE  answer.\n<br/><br/>Q.87    Neurotransmitter that stimulates release of prolactin from the pituitary.\n", answers: {a : "Acetylcholine", b : "Dopamine", c : "GABA", d : "Glutamate", e : "Glycine", f : "Histamine", g : "Noradrenaline", h : "Serotonin"}, correctAnswer: "h"},
{question: "For the following example of speech, please select the MOST APPROPRIATE phenomenology demonstrated.\n<br/><br/>Q.88    'Grass is green, violets are, um, blue. I was a fish, but then it didn't snow'\n", answers: {a : "Clanging", b : "Derailment", c : "Echolalia", d : "Palilalia", e : "Paraphasia", f : "Perseveration", g : "Tangentiality", h : "Thought blocking"}, correctAnswer: "b"},
{question: "For the following example, please select the MOST ACCURATE answer.\n<br/><br/>Q.89    A feature that does not suggest an underlying bipolar disorder in a patient presenting with depression.\n", answers: {a : "Late age of onset", b : "More than four previous episodes of depression", c : "Marked psychomotor slowing", d : "Postpartum onset", e : "Previous depressive episodes of short duration and rapid onset and offset", f : "Repeated loss of efficacy of antidepressants after an initial response", g : "Seasonal pattern to symptoms"}, correctAnswer: "a"},
{question: "For the following patient, please select the MOST LIKELY diagnosis.\n<br/><br/>Q.90    Gina, aged 25, develops chest pain and dizziness five weeks after commencing clozapine.\n", answers: {a : "Agranulocytosis", b : "Dehydration", c : "Hypernatremia", d : "Mitral valve prolapse", e : "Myocardial infarction", f : "Myocarditis", g : "Panic attack", h : "Pericardial effusion", i : "Somatisation", j : "Torsades des pointes"}, correctAnswer: "f"},
{question: "For the following patient, please select the MOST APPROPRIATE  next step in treatment.\n<br/><br/>Q.91    A 22 year old woman with bipolar disordered treated with olanzapine monotherapy presents with minimal verbal response, no response to instructions, and no visible movements.  All physical investigations are normal.\n", answers: {a : "Add Lithium", b : "Add Sodium Valproate", c : "Change antipsychotic", d : "Continue Olanzapine and start Lorazepam", e : "Continue Olanzapine and start Fluoxetine", f : "Continue Olanzapine and start Venlafaxine", g : "Electroconvulsive therapy", h : "Increase Olanzapine dose", i : "Stop Olanzapine and start Lorazepam", j : "Stop Olanzapine and start Lithium"}, correctAnswer: "i"},
{question: "For the following example, please select the MOST ACCURATE answer from the list below.\n<br/><br/>Q.92    Level II evidence as a mood stabiliser when combined with fluoxetine. \n", answers: {a : "Aripiprazole", b : "Citalopram", c : "Clozapine", d : "Fluoxetine", e : "Nortriptyline", f : "Olanzapine", g : "Quetiapine", h : "Risperidone", i : "Sertraline", j : "Venlafaxine"}, correctAnswer: "f"},
{question: "For the following patient, please select the MOST LIKELY dianosis from the list below.\n<br/><br/>Q.93    A 76 year old man develops a progressive condition causing drooling and micrographia.\n", answers: {a : "Alzheimer's dementia", b : "Binswanger's disease", c : "Creutzfeldt-Jakob disease", d : "Lewy body dementia", e : "Parkinson's disease", f : "Pick's disease", g : "Vascular dementia"}, correctAnswer: "e"},
{question: "For the following clinical situation, please select the MOST APPROPRIATE treatment regime.\n<br/><br/>Q.94    Initial target dose for Risperidone when treating first episode psychosis.\n", answers: {a : "0.5mg ' 1mg", b : "1mg ' 2mg", c : "2mg ' 3mg", d : "3mg ' 4mg", e : "4mg ' 5mg", f : "5mg ' 6mg"}, correctAnswer: "c"},
{question: "For the following example, please select the MOST ACCURATE statement from the list below.\n<br/><br/>Q.95    Issues to consider regarding treatments for bipolar depression.\n", answers: {a : "Antidepressants cause a switch to mania in 18% of cases", b : "Antidepressants cause a switch to mania in 38% of cases", c : "Antidepressants reduce the risk of rapid cycling", d : "ECT can cause a switch to mania", e : "Fluoxetine is safe to use as monotherapy", f : "Lamotrigine is effective for longer-term prevention, including during manic episodes", g : "Longer-term Lithium therapy increases the risk of suicide", h : "The risk of a switch to mania is reduced by the use of tricyclics"}, correctAnswer: "d"},
{question: "For the following example, please select the MOST APPROPRIATE historical author from the list below.\n<br/><br/>Q.96    Argued that male identification is defined by rejection rather than acceptance.\n", answers: {a : "Alfred Adler", b : "Anna Freud", c : "Erich Fromm", d : "Ernest Jones", e : "Harry Guntrip", f : "Heinz Kohut", g : "Karen Horney", h : "Mary Ainsworth", i : "Nancy Chodorow", j : "Otto Rank"}, correctAnswer: "i"},
{question: "For the following example, please select the MOST PRIORITISED ethical principle or right from the list below.\n<br/><br/>Q.97    A psychiatrist over-rides a patient's instruction not to contact her parents, due to concerns about the risk of her suiciding. \n", answers: {a : "Autonomy", b : "Beneficence", c : "Justice", d : "Non-maleficence", e : "The right not to be abused", f : "The right to be treated without prejudice or bias", g : "The right to be informed about one's treatment", h : "The right to be treated with dignity", i : "The right to privacy"}, correctAnswer: "b"},
{question: "For the following example, please select the MOST ACCURATE phenomenology demonstrated.\n<br/><br/>Q.98    'There are messages in car number plates about the conspiracy. It's the androids ' I have to stop them taking over.'\n", answers: {a : "Delusion of guilt", b : "Delusion of control", c : "Grandiose delusion", d : "Idea of reference", e : "Mood congruent delusion", f : "Nihilistic delusion", g : "Overvalued idea", h : "Preoccupation", i : "Referential delusion", j : "Somatic delusion"}, correctAnswer: "i"},
{question: "For the following example, please select the MOST ACCURATE answer from the list below.\n<br/><br/>Q.99    The most rapidly addictive activity.\n", answers: {a : "Casino-based blackjack", b : "Casino-based roulette", c : "Greyhound racing betting", d : "Horse racing betting", e : "On-line poker", f : "On-line mah jong", g : "Pokie machines", h : "Visiting internet social sites"}, correctAnswer: "g"},
{question: "For the following patient, please select the MOST LIKELY diagnosis listed below.\n<br/><br/>Q.100    Moira, a 76-year-old woman, is referred to you with depression. Her husband complains that she is having difficulty finding words and that she no longer cares for herself properly. Moira is dishevelled, with food stains on her blouse of which she seems unaware. Her speech shows poverty of content and paraphasias. She loses several points on cognitive assessment, with good short-term recall but inability to copy diagrams accurately or to write a proper sentence.\n", answers: {a : "Alzheimer's dementia", b : "Creutzfeld-Jakob disease", c : "Frontotemporal (Pick's) dementia", d : "Huntingdon's disease", e : "Korsakoff's syndrome", f : "Lewy body dementia", g : "Parkinson's disease", h : "Vascular dementia"}, correctAnswer: "c"},
{question: "For the following patient, please select the MOST APPROPRIATE linked medication.\n<br/><br/>Q.101    Sheila, aged 55, accepts that giving up marmite is worth it to help manage her previously intractable depression.\n", answers: {a : "Aripiprazole", b : "Clozapine", c : "Gabapentin", d : "Lamotrigine", e : "Lithium carbonate", f : "Olanzapine", g : "Phenelzine", h : "Quetiapine", i : "Risperidone", j : "Sodium valproate"}, correctAnswer: "g"},
{question: "For the following clinical situation, please select the MOST ACCURATE answer.\n<br/><br/>Q.102    Medication which is not considered a first line treatment for those with first episode non-affective psychosis.\n", answers: {a : "Amisulpride", b : "Aripiprazole", c : "Olanzapine", d : "Quetiapine", e : "Risperidone", f : "Ziprasidone"}, correctAnswer: "c"},
{question: "For the following example, please select the MOST RELEVANT aspect of memory demonstrated.\n<br/><br/>Q.103    'It's just like riding a bike.'\n", answers: {a : "Episodic Memory", b : "Facial Memory", c : "Paradigms", d : "Procedural Memory", e : "Semantic Memory", f : "Short-Term Memory", g : "Verbal Memory", h : "Working Memory"}, correctAnswer: "d"},
{question: "For the following patient, please select the MOST APPROPRIATE  diagnosis from the list below.\n<br/><br/>Q.104    Franz sees himself as the cause of a negative event for which in fact he was not primarily responsible. \n", answers: {a : "All-or-nothing thinking", b : "Automatic thoughts", c : "Catastrophising", d : "Disqualifying the positive", e : "Emotional reasoning", f : "Mislabelling", g : "Overgeneralization", h : "Personalization"}, correctAnswer: "h"},
{question: "For the following patient, please select the MOST LIKELY diagnosis.\n<br/><br/>Q.105    Billy is aged 8. His teacher has noticed that after getting to his classroom he leaves his bag, walks back to the gate, taps the gate eight times, does a push up and clenches and unclenches his fists three times, then goes back to class to put his bag away. \n", answers: {a : "Autistic Spectrum Disorder", b : "Conduct Disorder", c : "Disruptive Mood Dysregulation Disorder", d : "Obsessive Compulsive Disorder", e : "Oppositional Defiant Disorder", f : "Schizophrenia", g : "Social anxiety disorder"}, correctAnswer: "d"},
{question: "For the following example, please select the MOST ACCURATE  therapy demonstrated.\n<br/><br/>Q.106    Agnes, a 20 year old refugee, repeatedly draws figures who look vaguely like herself, but who have missing limbs or holes in their chests.  \n", answers: {a : "Acceptance and commitment therapy", b : "Behavioural therapy", c : "Brief psychodynamic therapy", d : "Cognitive behavioural therapy", e : "Expressive therapy", f : "Interpersonal therapy", g : "Play therapy", h : "Psychodrama"}, correctAnswer: "e"},
{question: "For the following question, please select the MOST ACCURATE answer.\n<br/><br/>Q.107    Which statement below is not correct, regarding Aboriginal and Torres Islander peoples and their health.\n", answers: {a : "Aboriginal and Torres Islander peoples have a holistic view of health.", b : "Finding out about traditional laws can play a big part in whether an assessment goes well or poorly.", c : "Psychiatrists need to recognise the history of physical and psychological genocide and extreme trauma affecting Aboriginal and Torres Strait Islander communities.", d : "Psychiatrists who do not themselves have Aboriginal or Torres Islander ancestry should read as much as possible about Aboriginal and Torres Islander cultural beliefs and practices so they can become experts in this field.", e : "'The Dance of Life' is a series of paintings of the many dimensions in a comprehensive approach to understand Aboriginal and Torres Strait Islander mental health.", f : "The RANZCP has apologised to Aboriginal and Torres Strait Islander peoples for the failure of the medical profession to intervene in the disastrous 'Stolen generation' practices.", g : "There are a very large number of Aboriginal tribes, whose languages are diverse.", h : "Understanding kinship systems is important when working with Aboriginal and Torres Islander peoples."}, correctAnswer: "d"},
{question: "For the following example please select the MOST ACCURATE psychological defence from the list below. \n<br/><br/>Q.108    Jodie tells her psychotherapist that she's started seeing a naturopath every week who is 'really understanding and helpful. It's such a relief to get practical advice.'\n", answers: {a : "Countertransference", b : "Idealisation and devaluation", c : "Intellectualisation", d : "Negative transference", e : "Positive transference", f : "Rationalisation", g : "Reaction formation", h : "Repression"}, correctAnswer: "b"},
{question: "For the following patient, please select the MOST ACCURATE brain region or pathway involved.\n<br/><br/>Q.109    A  4 year old child presents to ED with opisthotonus after ingesting her mother's metoclopramide tablets.\n", answers: {a : "Cerebellum", b : "Frontal cortex", c : "Hypothalamus", d : "Nigrostriatal system", e : "Right temporal area", f : "Spinothalamic pathway", g : "Temporal cortex", h : "Tuberoinfundibular pathway"}, correctAnswer: "d"},
{question: "For the following patient, please select the MOST IMPORTANT next investigation to order.\n<br/><br/>Q.110    Regarding people with Intellectual disability (ID), which of the following is not correct\n", answers: {a : "99% of people with Down's Syndrome develop Alzheimer's Disease by age 40", b : "ID is defined as: IQ <70, functional impairments in at least two areas of life, and onset before age 18", c : "Mild ID is defined as an IQ between 50'70", d : "Moderate ID is defined as an IQ between 35'49", e : "Of people with ID, 30% have additional visual disability", f : "Of people with ID, 40% have additional hearing disability", g : "People with ID are more vulnerable to mental disorders due to histories of abuse, adverse life events, and lack of protective experiences", h : "The incidence of suicide, drug & alcohol problems and personality disorders is higher in people with ID"}, correctAnswer: "h"},
{question: "For the following patient, please select the MOST APPROPRIATE diagnosis listed below.\n<br/><br/>Q.111    A 32 year old woman discusses her belief in the sixth sense, is circumstantial in her thinking and claims that the interviewer wore a certain ring because they knew she would like it.\n", answers: {a : "Brief Psychotic Disorder", b : "Delusional Disorder", c : "Narcissistic Personality disorder", d : "Major Depressive Disorder", e : "Obsessive Compulsive Disorder", f : "Paranoid Personality disorder", g : "Schizoaffective Disorder", h : "Schizophrenia", i : "Schizophreniform Disorder", j : "Schizotypal Personality Disorder", k : "Schizoid Personality Disorder"}, correctAnswer: "j"},
{question: "For the following clinical scenario, please select the MOST APPROPRIATE explanation listed below.\n<br/><br/>Q.112     Mrs Vodanovic suddenly develops an inability to speak during a bitter family dispute over her father's will. Her family bring her to the GP but she herself does not seem distressed.\n", answers: {a : "Catatonia", b : "Conversion disorder", c : "Elective mutism", d : "Fluent Dysphasia", e : "Guardedness", f : "Non-fluent dysphasia", g : "Passive-aggressive witholding", h : "Poverty of the content of speech", i : "Psychomotor retardation"}, correctAnswer: "b"},
{question: "For the following example, please select the MOST ACCURATE answer from the list below.\n<br/><br/>Q.113    Most effective follow-up therapy after a course of ECT for a patient with a serious major depression with melancholic features.\n", answers: {a : "Cognitive behavioural therapy and Fluoxetine", b : "Doxepin", c : "Doxepin and Sodium Valproate", d : "Lamotragine", e : "Lithium carbonate", f : "Mirtazepine", g : "Nortriptyline", h : "Nortriptyline and Lithium Carbonate", i : "Tranylcypromine", j : "Venlafaxine"}, correctAnswer: "h"},
{question: "For the following patient, please select the MOST APPROPRIATE  diagnosis listed below.\n<br/><br/>Q.114    William, an 80-year-old man with no psychiatric history, presents with a two-month history of low mood, isolativeness, visual hallucinations and nihilistic ruminations. Over the past month he has become almost mute, and bed-bound. Myoclonic jerks are observed, and an electroencephalogram (EEG) shows sharp wave complexes.\n", answers: {a : "Alzheimer's dementia", b : "Creutzfeld-Jakob disease", c : "Frontotemporal (Pick's) dementia", d : "Huntingdon's disease", e : "Lewy body dementia", f : "Neurosyphilis", g : "Parkinson's disease", h : "Vascular dementia", i : "Wernicke's encephalopathy"}, correctAnswer: "b"},
{question: "For the following clinical scenario, please select the MOST APPROPRIATE next investigation.\n<br/><br/>Q.115    A 35 year old man with a history of severe psychotic manic episodes developed neuroleptic malignant syndrome a year ago while on lithium and risperidone, and has been on no treatment for the last six months. He has now developed manic symptoms and has received high-dose oral quetiapine and intramuscular lorazepam for the last three days.\n", answers: {a : "Electrocardiogram", b : "Fasting serum glucose", c : "Full blood count", d : "Liver function tests", e : "Serum creatinine", f : "Serum creatinine kinase", g : "Temperature"}, correctAnswer: "g"},
{question: "For the following patient, please select the MOST ACCURATE  explanation listed below.\n<br/><br/>Q.116    After separating from her husband, Sandra is acutely sensitive to feeling criticized, sleeps more than usual and eats more high calorie junk food than usual.\n", answers: {a : "Anorexia nervosa", b : "Atypical depression", c : "Binge eating disorder", d : "Bipolar disorder type II", e : "Bulimia nervosa", f : "Comfort eating", g : "Dysthymic disorder", h : "Eating disorder NOS"}, correctAnswer: "b"},
{question: "For the following example, please select the MOST ACCURATE answer below.\n<br/><br/>Q.117    Tryptophan hydroxylase is the enzyme involved in the rate-limiting step in the synthesis of this neurotransmitter.\n", answers: {a : "5-hydroxy indole acetic acid (5-HIAA)", b : "Acetylcholine", c : "Dopamine", d : "Gamma-aminobutyric acid (GABA)", e : "Glutamate", f : "Glycine", g : "Noradrenaline", h : "Serotonin"}, correctAnswer: "h"},
{question: "For the following patient, please select the MOST APPROPRIATE  diagnosis listed below.\n<br/><br/>Q.118    Aya is a 60 year old immigrant who was brought here by her extended family a year ago. They regard her as 'slow' and she has been kept secluded, at home. She presents after developing delusions of being poisoned, and on assessment is noted to have a puffy face, long latency in replies and cognitive deficits.\n", answers: {a : "Cushings disease", b : "Graves disease", c : "Hyperparathyroidism", d : "Hyperthyroidism", e : "Hypothyroidism", f : "Liver failure", g : "Renal failure", h : "Wilson's disease"}, correctAnswer: "e"},
{question: "For the following patient, please select the MOST LIKELY  explanation from the list below.\n<br/><br/>Q.119    Mr Barker, aged 83, has such speech latency that he begins to reply only when the interviewer asks the next question. He makes no eye contact and has lost considerable weight.\n", answers: {a : "Alzheimer's dementia", b : "Catatonia", c : "Conversion disorder", d : "Elective mutism", e : "Normal pressure hydrocephalus", f : "Parkinson's disease", g : "Psychomotor retardation", h : "Schizophrenia"}, correctAnswer: "g"},
{question: "For the following patient, please select the MOST APPROPRIATE diagnosis from the list below.\n<br/><br/>Q.120    Joe, aged 32, has a history of recurrent depression and hypomania. He is admitted with an acute psychosis and becomes incoherent. Shortly afterwards he is found mute and immobile, standing upright but leaning at an odd angle.\n", answers: {a : "Catatonic schizophrenia", b : "Disorganised schizophrenia", c : "Malignant catatonia", d : "Manic stupor", e : "Melancholic depression", f : "Psychotic depression", g : "Schizoaffective disorder"}, correctAnswer: "d"},
{question: "For the following patient, please select the MOST IMPORTANT aspect of monitoring to have in place.\n<br/><br/>Q.121     A 41 year old man with schizophrenia is stable on clozapine, with good symptom control five months after commencing this.\n", answers: {a : "A fasting blood glucose level 3-monthly", b : "A monthly ECG", c : "An annual AIMs test", d : "Annual girth measurements", e : "Annual thyroid function tests", f : "Full blood count and differential monthly", g : "Full blood count and differential weekly", h : "Monthly serum levels of the medication", i : "Serum lipids annually", j : "Three-monthly HB1AC blood tests"}, correctAnswer: "f"},
{question: "For the following example, please select the MOST PRIORITISED ethical principle or right from the list below.\n<br/><br/>Q.122    Government funding to mental health services is 'ring fenced' to ensure the health service cannot use it to fund other specialties.\n", answers: {a : "Autonomy", b : "Beneficence", c : "Justice", d : "Non-maleficence", e : "The right not to be abused", f : "The right to be treated without prejudice or bias", g : "The right to be informed about one's treatment", h : "The right to be treated with dignity", i : "The right to privacy"}, correctAnswer: "c"},
{question: "For the following example, please select the MOST LIKELY diagnosis listed below. \n<br/><br/>Q.123    Maria is ordered to see a budgetary advisor and loses her job as a sales clerk due to theft.\n", answers: {a : "Alcohol abuse", b : "Alcohol dependence", c : "Heroin dependence", d : "Inhalant abuse", e : "Internet addiction", f : "Lorazepam dependence", g : "Pathological gambling", h : "Stimulant abuse"}, correctAnswer: "g"},
{question: "For the following patient, please select the MOST LIKELY diagnosis from the list below.\n<br/><br/>Q.124    Richard, a 72-year-old man with a history of past Coronary Artery Bypass Graft surgery and leg pain on walking, is referred as his wife has noticed problems with his short-term memory. Richard says that he copes by making lists. He presents as a pleasant and sociable man and scores 21/30 on a Mini Mental State Examination.\n", answers: {a : "Alzheimer's dementia", b : "Creutzfeld-Jakob disease", c : "Frontotemporal (Pick's) dementia", d : "Huntingdon's disease", e : "Lewy body dementia", f : "Parkinson's disease", g : "Vascular dementia"}, correctAnswer: "g"},
{question: "For the following patient, please select the MOST LIKELY diagnosis.\n<br/><br/>Q.125    Ray decides to cease penicillamine and starts naturopathy instead. Six months later he is admitted with a manic psychosis and cognitive deficits.\n", answers: {a : "Cushings disease", b : "Graves disease", c : "Hypothyroidism", d : "Liver failure", e : "Phaeochromocytoma", f : "Porphyria", g : "Renal failure", h : "SIADH", i : "Wilson's disease"}, correctAnswer: "i"},
{question: "For the following patient, please select the MOST LIKELY diagnosis from the list below.\n<br/><br/>Q.126    A young man is repeatedly admitted with relapses after stopping clozapine. The relapses always have the same pattern of symptoms, with muteness, echopraxia and waxy flexibility.\n", answers: {a : "Catatonic schizophrenia", b : "Disorganised schizophrenia", c : "Malignant catatonia", d : "Manic stupor", e : "Melancholic depression", f : "Neuroleptic malignant syndrome", g : "Psychotic depression", h : "Schizoaffective disorder"}, correctAnswer: "a"},
{question: "For the following example, please select the MOST ACCURATE answer from the list below.\n<br/><br/>Q.127    The main morphological findings in human postmortem studies of schizophrenia.\n", answers: {a : "Decreased hippocampal volume", b : "Enlargement of ventricles", c : "Increased neuronal density in Brodman areas 9 and 46", d : "Increased thalamic volume", e : "Reduction in dendritic spaces", f : "Slight cortical thinning in prefrontal cortex"}, correctAnswer: "d"},
{question: "For the following patient, please select the MOST APPROPRIATE medication from the list below.\n<br/><br/>Q.128    Benjy is a 13 year old boy with a long history of ADHD, which is considered well treated on Methylphenidate LA.  He has developed a major depression episode with marked loss of appetite and sleep disruption, which his mother ascribes to difficulties with learning and a family history of depression.\n", answers: {a : "Atomoxetine", b : "Caffeine", c : "Citalopram", d : "Concerta (Methylphenidate XR)", e : "Dexamphetamine", f : "Fluoxetine", g : "Melatonin", h : "Modafinil", i : "Risperidone"}, correctAnswer: "f"},
{question: "For the following symptoms in neonates, which medication, if used during pregnancy, is the MOST LIKELY cause. \n<br/><br/>Q.129    Jitteriness, poor feeding, hypotonia and tachypnoea. \n", answers: {a : "Benztropine", b : "Gabapentine", c : "Lithium carbonate", d : "Olanzapine", e : "Paroxetine", f : "Quetiapine", g : "Risperidone", h : "Tranylcypromine"}, correctAnswer: "e"},
{question: "For the following example, please select the MOST APPROPRIATE aspect of qualitative research from the list below.\n<br/><br/>Q.130    A qualitative study describing and analysing organisational change during the restructuring of a maternal mental health service, across one year.\n", answers: {a : "Constant Comparative Analysis", b : "Data collection using documentation", c : "Data collection using focus groups", d : "Data collection using semi-structured interviews", e : "Ethnographic qualitative research", f : "Extended case study", g : "Grounded Theory", h : "Phenomenological qualitative research"}, correctAnswer: "f"},
{question: "For the following example, please select the MOST APPROPRIATE type of psychotherapy.\n<br/><br/>Q.131    Requires the client to have clearly defined goals and minimal resistance.\n", answers: {a : "Adherence therapy", b : "Brief psychodynamic psychotherapy", c : "Cognitive behavioural therapy", d : "Dialectical behavioural therapy", e : "Exposure and response prevention", f : "Interpersonal therapy", g : "Motivational interviewing", h : "Solution-focussed therapy", i : "Supportive therapy", j : "Systematic desensitisation"}, correctAnswer: "b"},
{question: "For the following patient, please select the MOST LIKELY  causative medication listed below.\n<br/><br/>Q.132    A woman being treated for persistent depression develops fever, fatigue and mouth ulceration.\n", answers: {a : "Aripiprazole", b : "Clozapine", c : "Gabapentin", d : "Lamotrigine", e : "Lithium carbonate", f : "Olanzapine", g : "Phenelzine", h : "Quetiapine", i : "Risperidone", j : "Sodium valproate"}, correctAnswer: "d"},
{question: "For the following question, please select the MOST ACCURATE answer from the list below.  \n<br/><br/>Q.133    Which of the following is not a diagnostic feature of Borderline Personality Disorder.\n", answers: {a : "Affective instability", b : "Chronic feelings of emptiness", c : "Difficulty controlling anger", d : "Dissociative symptoms", e : "Disturbed Identity", f : "Efforts to avoid abandonment", g : "Impulsivity in areas that are self-damaging", h : "Recurrent suicidal (or self-mutilating) behaviour", i : "Stress related paranoid ideation", j : "Suggestibility"}, correctAnswer: "j"},
{question: "For the following example, please select the MOST ACCURATE type of memory demonstrated. \n<br/><br/>Q.134    Miriam can name three female Prime Ministers of New Zealand.\n", answers: {a : "Episodic Memory", b : "Facial Memory", c : "Imagery", d : "Paradigms", e : "Procedural Memory", f : "Semantic Memory", g : "Short-Term Memory", h : "Verbal Memory", i : "Visual Memory", j : "Working Memory"}, correctAnswer: "f"},
{question: "For the following example, please select the MOST ASSOCIATED historical figure listed below.\n<br/><br/>Q.135    Winner of the Nobel Prize in 1927 for discovery of the therapeutic value of malaria inoculation in the treatment of dementia paralytica.\n", answers: {a : "Carl Jung", b : "Emil Kraepelin", c : "Eugene Bleuler", d : "Franz Gall", e : "Hideyo Noguchi", f : "Julius Wagner-Jauregg", g : "Karl Menninger", h : "Ugo Cerletti"}, correctAnswer: "f"},
{question: "For the following example, please select the MOST ACCURATE legal concept demonstrated. \n<br/><br/>Q.136    A young woman kills her mother, convinced that she is an impostor and a spy.  \n", answers: {a : "Actus reus", b : "Disease of the mind", c : "Duress", d : "Fitness to plead", e : "Forseeability", f : "Irresistible impulse", g : "Mens rea", h : "Natural Justice", i : "Provocation", j : "Sane Automatism"}, correctAnswer: "b"},
{question: "For the following example, please select the MOST ASSOCIATED genetic risk factor.\n<br/><br/>Q.137    Increased risk of late-onset Alzheimer's disease.\n", answers: {a : "5HTT gene L genotype", b : "5HTT gene S genotype", c : "Apolipoprotein gene (APOE e4 allele)", d : "D-amino acid oxidase activator (DAOA)", e : "Neuregulin gene (NRG1)", f : "Neurogenic locus notch 4 (NOTCH4)", g : "Reelin gene (REELIN)"}, correctAnswer: "c"},
{question: "For the following question, please select the MOST ACCURATE answer from the list below.\n<br/><br/>Q.138    Which of the following is not true, when working with an interpreter.\n", answers: {a : "Family members may not be able to interpret accurately for a number of reasons.", b : "Interpreters for the deaf should be seated beside the clinician.", c : "Interpreters must adhere to strict confidentiality.", d : "Interpreters should not have side conversations with the patient or family.", e : "Interpreters should preferentially use the 'triangle' model of interpretation.", f : "Interpreters should preferentially use the 'black box' model of interpretation.", g : "When working with an interpreter, speak directly to the patient."}, correctAnswer: "f"},
{question: "For the following clinical problem, please select the MOST LIKELY cause below.\n<br/><br/>Q.139    Keratinocyte apoptosis.\n", answers: {a : "Acute laryngeal dystonia", b : "Anticholinergic delirium", c : "Fatal carbon monoxide poisoning", d : "Fatal paracetamol overdose", e : "Heavy cigarette smoking", f : "Lithium toxicity", g : "Opiate toxicity", h : "Stevens-Johnson syndrome"}, correctAnswer: "h"},
{question: "For the following clincial example, please select the MOST APPROPRIATE medication listed below. \n<br/><br/>Q.140    Elias is a 14 year old boy with significant autistic spectrum features and an IQ of 72.  He has devoted parents who have worked hard on behavioural routines.  Since puberty, they have been struggling with increasing episodes of irritability when his needs are not met immediately and have asked about medication options.\n", answers: {a : "Atomoxetine", b : "Caffeine", c : "Citalopram", d : "Concerta (Methylphenidate XR)", e : "Dexamphetamine", f : "Fluoxetine", g : "Modafinil", h : "Olanzapine", i : "Risperidone"}, correctAnswer: "i"},
{question: "CAP: \n<br/><br/><img src='1_1.png'/><br/><br/>Question 1.1      Based on the adjoining abstract and your other knowledge, please answer the following question. <br/>Which option best describes this study?  (1 mark)\n", answers: {a : "Aetiological", b : "Interventional", c : "Meta-analysis", d : "Observational", e : "Prognositic", f : "Qualitative", g : "Screening intervention", h : "Systematic review"}, correctAnswer: "c"},
{question: "CAP: \n<br/><br/><img src='1_2to1_3.png'/><br/><br/>Question 1.2    Based on the adjoining abstract and your other knowledge, please answer the following question. <br/>Which option best describes the main study screening process? (2 marks)\n", answers: {a : "Contacting individual study authors", b : "Manual search", c : "Narrative review", d : "Regulatory agencies enquiry", e : "Scoping review", f : "Systematic literature search", g : "Trial registry search"}, correctAnswer: "f"},
{question: "CAP: \n<br/><br/><img src='1_2to1_3.png'/><br/><br/>Question 1.3    Based on the adjoining abstract and your other knowledge, please answer the following question. <br/>Which option best describes the double-blind nature of the included studies? (2 marks)\n", answers: {a : "A study in which participants and their family are unaware of whether participants are receiving  treatment with the active drug or placebo.", b : "A study in which treatment providers and researchers are unaware of whether participants are receiving treatment with the active drug or placebo.", c : "A study in which participants are unaware of whether they are receiving treatment with the active drug or placebo.", d : "A study in which the participants and researchers are unaware whether the participants are receiving treatment with the active drug or placebo.", e : "A study in which the researchers and data analysts are unware whether the participants are receiving treatment with the active drug or placebo.", f : "A study in which the participants and data analysts are unaware whether the participants are receiving treatment with the active drug or placebo."}, correctAnswer: "d"},
{question: "CAP: \n<br/><br/><img src='1_4.png'/><br/><br/>Question 1.4     Based on the adjoining figure and your other knowledge, please answer the following question. <br/>Which option below best describes the principal advantage of network meta-analyses? (2 marks) \n", answers: {a : "Allows direct comparisons between treatments of interest.", b : "Analyses longitudinal cohort data to make inferences about causation.", c : "Compares treatments of interest when direct comparisons are not present through the use of a common comparator or linking treatment.", d : "Ensures unpublished, often negative studies are included in the analysis.", e : "Excludes those who do not adhere to treatment.", f : "Increases the statistical power."}, correctAnswer: "c"},
{question: "CAP: \n<br/><br/><img src='1_5.png'/><br/><br/>Question 1.5    Based on the adjoining abstract and your other knowledge, please answer the following question. <br/>Which option best describes the Odds Ratio calculation?  (2 marks)\n", answers: {a : "A measure of the strength of the association.", b : "The inverse of the absolute risk reduction.", c : "The odds of achieving remission for antidepressants divided by the odds of achieving remission in placebo.", d : "The proportion of patients who have responded over a given time period.", e : "The rate of remission for antidepressants minus the rate of remission for placebo.", f : "The ratio of achieving remission for antidepressants divided by the ratio of achieving remission in placebo."}, correctAnswer: "c"},
{question: "CAP: \n<br/><br/><img src='1_6.png'/><br/><br/>Question 1.6     Based on the adjoining figure A and your other knowledge, please answer the following question. <br/>Which statement about efficacy is most accurate?  (2 marks)\n", answers: {a : "Amitriptyline is significantly more efficacious than Mirtazapine.", b : "Amitriptyline is the antidepressant of first choice.", c : "Clomipramine is significantly less effective than Agomelatine.", d : "Clomipramine is the least efficacious antidepressant.", e : "Reboxetine is significantly less efficacious than Amitriptyline.", f : "Reboxetine is significantly more efficacious than Amitriptyline.", g : "Reboxetine is the weakest antidepressant."}, correctAnswer: "e"},
{question: "CAP: \n<br/><br/><img src='1_7.png'/><br/><br/>Question 1.7     Based on the adjoining figure B and your other knowledge, please answer the following question. <br/>Which statement about acceptability is most accurate?  (2 marks)\n", answers: {a : "Agomelatine is significantly more acceptable than Clomipramine", b : "Agomelatine is significantly more acceptable than Fluoxetine", c : "Agomelatine is the antidepressant of first choice", d : "Amitriptyline is significantly more acceptable than Reboxetine", e : "Amitriptyline is the most acceptable medication", f : "Clomipramine is significantly more acceptable than Amitriptyline", g : "Clomipramine is significantly more acceptable than placebo"}, correctAnswer: "a"},
{question: "CAP: \n<br/><br/><img src='1_8.png'/><br/><br/>Question 1.8    Based on the adjoining figure and your other knowledge, please answer the following question. <br/>Which statement about funnel plots is most accurate?  (2 marks)\n", answers: {a : "Between study heterogeneity is not a cause of funnel plot asymmetry.", b : "Chance findings do not cause funnel plot asymmetry.", c : "Consistent negative findings between active treatment and placebo causes funnel plot asymmetry.", d : "Fraudulent reporting of study results is not a cause of funnel plot asymmetry.", e : "Non-publication of smaller negative studies is a cause of funnel plot asymmetry.", f : "Reporting bias does not cause funnel plot asymmetry.", g : "Reporting studies with large variation in sample sizes causes funnel plot asymmetry."}, correctAnswer: "e"},
{question: "CAP: \n<br/><br/><img src='1_9.png'/><br/><br/>Question 1.9   Based on the adjoining abstract excerpt and your other knowledge, please answer the following question. <br/>Which statement about risk of bias is most accurate?  (2 marks)\n", answers: {a : "Failure to blind assessors increases risk of bias.", b : "Lack of randomisation reduces risk of bias.", c : "Similar findings from a series of studies reduces risk of bias.", d : "The author/s of the study assess risk of bias based on their qualitative impression.", e : "The drop out of non-responders will reduce risk of bias.", f : "The lead author of the study is best placed to complete the risk of bias assessment."}, correctAnswer: "a"},
{question: "CAP: \n<br/><br/><img src='1_10.png'/><br/><br/>Question 1.10     Based on the adjoining abstract excerpt and your other knowledge, please answer the following question. Which statement about quality of evidence is most accurate?  (1 mark)\n", answers: {a : "A case series from a dedicated clinician is more informative than a case-control study.", b : "A systematic review of RCTs provides high level evidence to inform medical decision making.", c : "Expert opinion provides the best quality evidence for medical decision making.", d : "Several medium scale RCTs provide more useful information than one large RCT for informing medical decision making.", e : "The management of rare conditions is best evaluated with large scale RCTs."}, correctAnswer: "b"},
{question: "CAP: \n<br/><br/><img src='1_11.png'/><br/><br/>Question 1.11     Based on the adjoining abstract excerpt and your other knowledge, please answer the following question. A factor most likely to limit the generalisability of these results to your own clinical work would be?  (2 marks)\n", answers: {a : "Clinicians often combine other agents (such as hypnotics) with antidepressants to provide immediate symptom relief.", b : "Patients recruited into studies such as those included tend to be highly selected.", c : "Patients with bipolar depression likely contaminated the study results.", d : "Relevant antidepressant medications weren't included in the analysis.", e : "Study lacked power to demonstrate meaningful results.", f : "The doses of antidepressant medications used would be likely to differ from those in Australasian practice.", g : "The grey literature wasn't taken into consideration."}, correctAnswer: "b"},
{question: "CAP: \n<br/><br/><img src='2_1to2_2.png'/><br/><br/>Question 2.1    Based on the adjoining abstract and your other knowledge, please answer the following question. <br/>Which statement best describes the design of this study?  (1 mark)\n", answers: {a : "Case-control study", b : "Cohort study", c : "Cross sectional study", d : "Prospective study", e : "Pseudorandomised control study", f : "Randomised controlled trial", g : "Systematic review"}, correctAnswer: "d"},
{question: "CAP: \n<br/><br/><img src='2_1to2_2.png'/><br/><br/>Question 2.2    Based on the adjoining abstract and your other knowledge, please answer the following question. <br/>This trial was designed to measure the differences in:  (1 mark)\n", answers: {a : "3'hydroxycotinine in smokers", b : "NMR in tobacco users", c : "Puff volume between normal and fast metabolisers", d : "Quit success in smokers", e : "Smoking cessation differences between slow and fast metabolisers", f : "Smoking topography between normal and slow metabolisers", g : "Tobacco use patterns in smokers"}, correctAnswer: "f"},
{question: "CAP: \n<br/><br/><img src='2_3to2_4.png'/><br/><br/>Question 2.3    Based on the abstract, the adjoining extract and your other knowledge, which of the following statements is true regarding the study setting:   (1 mark)\n", answers: {a : "A clinical setting", b : "A mix of clinical and naturalistic settings", c : "A naturalistic based setting", d : "None of the above"}, correctAnswer: "c"},
{question: "CAP: \n<br/><br/><img src='2_3to2_4.png'/><br/><br/>Question 2.4    Based on the abstract, the adjoining extract and your other knowledge, please answer the following question.<br/>Patients were included this study if they:  (1 mark)\n", answers: {a : "Lived in the USA and were adults and cigarette smokers", b : "Smoked at least 7 cigarettes per week and lived in Pennsylvania", c : "Smoked non-tobacco products and lived in Pennsylvania", d : "Smoked on a daily basis and lived in Pennsylvania", e : "Were aged 17 and over and lived in Pennsylvania", f : "Were being treated for anxiety"}, correctAnswer: "d"},
{question: "CAP: \n<br/><br/><img src='2_5.png'/><br/><br/>Question 2.5    Based on the abstract above and your other knowledge, the SPA-M device does not measure:  (2 marks)\n", answers: {a : "Aberrant flows", b : "Cigarettes per day", c : "Number of cigarettes smoked", d : "Quality of cigarette smoke", e : "Smoking topography"}, correctAnswer: "d"},
{question: "CAP: \n<br/><br/><img src='2_6to2_7.png'/><img src='2_6Ato2_7.png'/><br/><br/>Question 2.6    Based on the adjoining extract and tables, the abstract and your other knowledge, the mean NMR is:  (1 mark)\n", answers: {a : "0.46", b : "0.38", c : "Highest in a black male", d : "Highest in a white female", e : "Highest in females of other race", f : "Lowest in a white male"}, correctAnswer: "d"},
{question: "CAP: \n<br/><br/><img src='2_6to2_7.png'/><img src='2_6Ato2_7.png'/><br/><br/>Question 2.7    Based on the adjoining extract and tables, the abstract and your other knowledge, the total number of participants was: (1 mark)\n", answers: {a : "299", b : "326", c : "351", d : "352", e : "652"}, correctAnswer: "b"},
{question: "CAP: \n<br/><br/>Question 2.8    Based on your other knowledge, which of these is not a continuous variable?  (1 mark)\n", answers: {a : "Age", b : "BMI", c : "Female sex", d : "Nicotine metabolite ratio", e : "Number of cigarettes per day", f : "Puff duration"}, correctAnswer: "c"},
{question: "CAP: \n<br/><br/>Question 2.9    Based on your other knowledge, which of the following assumptions must be met in an ANOVA:  (2 marks)\n", answers: {a : "All of these things", b : "Random sampling of cases must have taken place", c : "The data must be normally distributed", d : "The dependent variable must be interval or ratio", e : "There must be homogeneity of variance", f : "There must be only one dependent variable"}, correctAnswer: "a"},
{question: "CAP: \n<br/><br/>Question 2.10    Based on your other knowledge, the p value represents:  (2 marks)\n", answers: {a : "The largest significance level at which the null hypothesis can be rejected", b : "The largest significance level at which the null hypothesis cannot be rejected", c : "The probability that errors have been made in rejecting or not rejecting the null hypothesis", d : "The smallest significance level at which the null hypothesis can be rejected", e : "The smallest significance level at which the null hypothesis cannot be rejected"}, correctAnswer: "d"},
{question: "CAP: \n<br/><br/><img src='2_11.png'/><br/><br/>Question 2.11     Based on the adjoining table, the abstract and your other knowledge, choose the most accurate statement:  (2 marks)\n", answers: {a : "Age and sex have not been adjusted for in this table", b : "A p value of 0.0898 is statistically significant", c : "FTND and HONC while not displayed are likely to be higher in slow metabolisers", d : "Higher levels were found for total daily puffs in normal metabolisers", e : "Higher NMR was significantly associated with total daily puffs", f : "Lower NMR was significantly associated with total daily puff volume", g : "Normal metabolisers had significantly lower mean levels of cigarettes per day"}, correctAnswer: "e"},
{question: "CAP: \n<br/><br/><img src='2_12.png'/><br/><br/>Question 2.12     Based on the adjoining excerpt and your other knowledge, in this study internal consistency means:  (1 mark)\n", answers: {a : "Highly correlated items can be removed", b : "The Cronbach's alpha is likely to be high", c : "The items all measured different things", d : "The items all measured the same thing", e : "The measures used were valid", f : "The study consistently used good measures"}, correctAnswer: "b"},
{question: "CAP: \n<br/><br/>Question 2.13     Based on the abstract, extracts and tables provided and your other knowledge, which of the following is not a likely limitation of the study:  (2 marks)\n", answers: {a : "Measuring saliva not blood levels of nicotine metabolites", b : "Not all information was gathered on factors that would impact on blood nicotine levels ' e.g. oral contraceptives", c : "Participants may have smoked cigarettes not using the device", d : "Smokers would not find a simple topography device easy to use", e : "The use of the topography device may alter smoking behaviours"}, correctAnswer: "a"},
{question: "CAP: \n<br/><br/>Question 2.14     Based on the abstract, extracts and tables provided and your other knowledge, which of the following statements is a conclusion of the study:  (2 marks)\n", answers: {a : "Cigarette puffing in a clinical setting does not differ from a naturalistic enviroment", b : "Individual differences in nicotine metabolism are associated with smoke exposure", c : "Low metabolisers are more dependent on nicotine", d : "NMR is associated with tobacco use behaviours", e : "Smokers do not smoke more intensively when under observation", f : "The biological dose of tobacco exposure is attributed only to the frequency of smoking"}, correctAnswer: "d"},
    // Final Slide
    {
        question: "THIS IS THE LAST SLIDE OF THE MOCK EXAM. <br/><br/><em>IF YOU ARE FINISHED</em><br/> --Then CLICK the -SUBMIT QUIZ- button ABOVE. <br/>--SCROLL DOWN to the BOTTOM OF THIS WINDOW to see <em>YOUR FINAL RESULT.</em><br/><br/>---AFTERWARDS, you can press the -PREVIOUS QUESTION- & -NEXT QUESTION- buttons to review your answers:<br/>----Questions you answered CORRECTLY are in <font color='green'>GREEN </font><br/>----Questions you answered INCORRECTLY are in <font color='red'>RED </font><br/><br/><font color='gray'><em>You can click the right mouse button at the bottom of this page if you also want to print the results</em></font><br/><br/><br/><em>IF YOU ARE NOT FINISHED</em><br/>--Then DON'T press the -SUBMIT QUIZ- button. <br/> --INSTEAD, press the -PREVIOUS QUESTION- button to review past questions. <br/>--You will need to press the -NEXT SLIDE- button until you return to this page to find the -SUBMIT QUIZ- button.<br/><br/>!GOOD LUCK!",
        answers: {  },
        correctAnswer: ""
    },



];

function buildQuiz() {
// we'll need a place to store the HTML output
const output = [];

// for each question...
myQuestions.forEach((currentQuestion, questionNumber) => {
  // we'll want to store the list of answer choices
  const answers = [];

  // and for each available answer...
  for (letter in currentQuestion.answers) {
    // ...add an HTML radio button
    answers.push(
      `<label>
         <input type="radio" name="question${questionNumber}" value="${letter}">
          ${letter} :
          ${currentQuestion.answers[letter]}
       </label>`
    );
  }

  // add this question and its answers to the output
  output.push(
    `<div class="slide">
       <div class="question"> ${currentQuestion.question} </div>
       <div class="answers"> ${answers.join("")} </div>
     </div>`
  );
});

// finally combine our output list into one string of HTML and put it on the page
quizContainer.innerHTML = output.join("");
}

function showResults() {
// gather answer containers from our quiz
const answerContainers = quizContainer.querySelectorAll(".answers");

// keep track of user's answers
let numCorrect = 0;

// for each question...
myQuestions.forEach((currentQuestion, questionNumber) => {
  // find selected answer
  const answerContainer = answerContainers[questionNumber];
  const selector = `input[name=question${questionNumber}]:checked`;
  const userAnswer = (answerContainer.querySelector(selector) || {}).value;

  // if answer is correct
  if (userAnswer === currentQuestion.correctAnswer) {
    // add to the number of correct answers
    numCorrect++;

    // color the answers green
    answerContainers[questionNumber].style.color = "lightgreen";
  } else {
    // if answer is wrong or blank
    // color the answers red
    answerContainers[questionNumber].style.color = "red";
  }
});

var percentage = (numCorrect/(myQuestions.length-1)) * 100;
var passingMark = 55;


// show number of correct answers out of total


resultsContainer.innerHTML = `The 2017 RANZCP MCQ passing mark was ${passingMark}%. <br/>Your final exam score is: ${percentage}%        (${numCorrect} out of ${myQuestions.length})`;
resultsContainer.style.color = "red";


}

function showSlide(n) {
slides[currentSlide].classList.remove("active-slide");
slides[n].classList.add("active-slide");
currentSlide = n;

if (currentSlide === 0) {
  previousButton.style.display = "none";
} else {
  previousButton.style.display = "inline-block";
}

if (currentSlide === slides.length - 1) {
  nextButton.style.display = "none";
  submitButton.style.display = "inline-block";
} else {
  nextButton.style.display = "inline-block";
  submitButton.style.display = "none";
}
}

function showNextSlide() {
showSlide(currentSlide + 1);
}

function showPreviousSlide() {
showSlide(currentSlide - 1);
}

const quizContainer = document.getElementById("quiz");
const resultsContainer = document.getElementById("results");
const submitButton = document.getElementById("submit");

// display quiz right away
buildQuiz();

const previousButton = document.getElementById("previous");
const nextButton = document.getElementById("next");
const slides = document.querySelectorAll(".slide");
let currentSlide = 0;

showSlide(0);

// on submit, show results
submitButton.addEventListener("click", showResults);
previousButton.addEventListener("click", showPreviousSlide);
nextButton.addEventListener("click", showNextSlide);
};
document.onload = quizfunction();
